# Usign the Clean Blog theme

title: Laís
author: laisdallemulle
email: laisdallemulle@gmail.com
description: Personal site
baseurl: ""
url: "https://laisdallemulle.github.io/"
github_username:  laisdallemulle

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
exclude: ["node_modules"]

name: laisdallemulle
gems:
  - jekyll-feed
  - jekyll-paginate
